# Generated by Django 3.2.3 on 2022-09-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirtelPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prices', models.CharField(max_length=200)),
                ('validity', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('sms', models.CharField(max_length=200)),
                ('calldetails', models.CharField(max_length=200)),
                ('amazon', models.CharField(max_length=200)),
                ('benifit', models.CharField(max_length=200)),
            ],
        ),
    ]
